---

name: "Quality"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  check-quality:
    runs-on: "ubuntu-latest"
    steps:
      # setup
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4
      - uses: "DeterminateSystems/nix-installer-action@ve50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d" # v16
        with:
          diagnostic-endpoint: ""
      - uses: "DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4" # v9
        with:
          diagnostic-endpoint: ""
      - name: "Print flake metadata"
        run: "nix flake metadata"
      - uses: "DeterminateSystems/flake-checker-action@078f5f7f47ee188aa6cb472527ca5984e195222d" # v9
        with:
          fail-mode: true
          ignore-missing-flake-lock: false
          nixpkgs-keys: "nixpkgs-unstable,nixpkgs-stable"
          send-statistics: false
      - name: "Setup shell"
        run: "nix develop --command true"

      # tests
      - name: "Flake check"
        run: "nix flake check --all-systems --print-build-logs"

      - name: "Files respect Editorconfig configuration"
        run: "nix develop --command lint-editorconfig"

      - name: "Files respect treefmt format"
        run: |
          # we need to explicitly add all formatters except cue
          # this is due to cue re-generating files, which would cause --fail-on-change to fail.
          nix develop --command           \
            treefmt                       \
              --no-cache --fail-on-change \
              --formatters alejandra      \
              --formatters jsonfmt        \
              --formatters mdformat       \
              --formatters mdsh           \
              --formatters shfmt          \
              --formatters yamlfmt

      - name: "Lint Github Actions"
        run: "nix develop --command lint-ghaction"

      - name: "Lint Shell scripts"
        run: "nix develop --command lint-sh"

      - name: "Lint Yaml configurations files"
        run: "nix develop --command lint-yaml"

      - name: "Lint Nix code"
        run: "nix develop --command lint-nix"
